<?php
require('testable.php');
require('spec.php');
require('spec_description.php');
require('spec_context.php');
require('spec_subject.php');
require('spec_stub.php');
require('spec_double.php');
require('square_functions.php');
?>